name: Codex Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  codex:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@codex')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@codex')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@codex')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@codex') || contains(github.event.issue.title, '@codex')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Codex Code
        id: codex
        uses: ./ # Use the local action
        with:
          # Use Codex instead of Claude
          use_codex: "true"
          # Let action use GitHub App authentication (OIDC) - do not pass github_token

          # Codex-specific configuration
          trigger_phrase: "@codex" # 关键修复：设置 Codex 触发词
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: ${{ secrets.OPENAI_BASE_URL }} # Optional: for custom endpoints

          # Keep the same tool permissions as Claude version
          claude_args: |
            --allowedTools "Bash(bun install),Bash(bun test:*),Bash(bun run format),Bash(bun typecheck)"
